import { readFileSync } from "node:fs";import path from "node:path";import { describe,expect,it } from "vitest";
const migration=readFileSync(path.resolve("supabase/migrations/202607130005_customers_orders_payments.sql"),"utf8");const sql=readFileSync(path.resolve("supabase/tests/rls_sales.sql"),"utf8");
describe("migración de ventas",()=>{
it("crea tipos, tablas, RLS y no concede DELETE",()=>{for(const t of ["customers","orders","order_items","payments"]){expect(migration).toContain(`create table public.${t}`);expect(migration).toContain(`alter table public.${t} enable row level security`)}expect(migration).not.toMatch(/using\s*\(\s*true\s*\)/i);expect(migration).not.toMatch(/grant[^;]*delete/i);});
it("amplía el libro mayor con referencias exactas",()=>{for(const v of ["sale_reservation","reservation_release","sale_dispatch","customer_return","inventory_movements_order_line_fkey","order_items_balance_identity_fkey","order_items_order_balance_unique"])expect(migration).toContain(v);expect(migration).toContain("version=version+1");});
it("implementa transiciones y pagos",()=>{for(const f of ["submit_order","return_order_to_draft","confirm_order","cancel_order","dispatch_order_item","dispatch_order","deliver_order","return_order_item","confirm_payment","cancel_payment","refund_payment","admin_financial_reconciliation"])expect(migration).toContain(`function public.${f}`);expect(migration).toContain("private.start_inventory_command");});
it("protege PII y autorización",()=>{expect(migration).toContain("Solo un administrador puede cambiar el estado del cliente");expect(migration).toContain("private.assert_inventory_operator(true)");expect(migration).not.toMatch(/metadata[^;]*(email|phone|address|document_number)/i);});
it("incluye script ficticio con rollback y escenarios críticos",()=>{for(const s of ["oversell_rejected","reservation_without_physical_change","partial_dispatch_exact","operator_refund_denied","anonymous_customers_denied","confirm_order_concurrency_two_connections"])expect(sql).toContain(s);expect(sql.toLowerCase()).toContain("rollback;");});
});
