import { readFileSync } from "node:fs";import path from "node:path";import { describe,expect,it } from "vitest";
const migration=readFileSync(path.resolve("supabase/migrations/202607140006_shipments.sql"),"utf8");
const sql=readFileSync(path.resolve("supabase/tests/rls_shipping.sql"),"utf8");
describe("migración logística",()=>{
  it("es atómica y crea el modelo de Etapa 5A",()=>{expect(migration.match(/^begin;/gim)).toHaveLength(1);expect(migration.match(/^commit;/gim)).toHaveLength(1);expect(migration.trim().endsWith("commit;")).toBe(true);for(const table of ["carriers","shipments","shipment_items","shipment_events"])expect(migration).toContain(`create table public.${table}`);});
  it("mantiene eventos inmutables y sin escrituras directas",()=>{expect(migration).toContain("shipment_events_reject_update");expect(migration).toContain("shipment_events_reject_delete");expect(migration).not.toMatch(/grant[^;]*(?:insert|update|delete)[^;]*shipment_events/i);expect(migration).not.toMatch(/create policy[^;]*delete/i);expect(migration).not.toMatch(/using\s*\(\s*true\s*\)/i);});
  it("protege cantidades y pertenencia al pedido",()=>{expect(migration).toContain("shipment_items_shipment_order_fkey");expect(migration).toContain("shipment_items_order_line_fkey");expect(migration).toContain("assigned+p_quantity>item.dispatched_quantity-item.returned_quantity");expect(migration).toContain("for update");});
  it("expone solo las RPC públicas previstas",()=>{for(const fn of ["create_shipment","add_shipment_item","remove_shipment_item","mark_shipment_ready","hand_shipment_to_carrier","add_shipment_transit_event","register_delivery_attempt","deliver_shipment","start_shipment_return","complete_shipment_return","cancel_shipment","admin_shipping_reconciliation"])expect(migration).toContain(`public.${fn}`);expect(migration).not.toMatch(/grant execute[^;]*private\./i);expect(migration).toContain("set search_path=''");});
  it("conserva estados comerciales, financieros y logísticos separados",()=>{expect(migration).not.toMatch(/update public\.(orders|payments|inventory_balances|inventory_movements)/i);expect(migration).toContain("create type public.shipment_status");expect(migration).not.toContain("public.movement_type");});
  it("incluye pruebas SQL ficticias y rollback",()=>{for(const value of ["anonymous_denied","inactive_denied","operator_carrier_write_denied","cross_order_item_rejected","quantity_above_dispatched_rejected","event_update_rejected","event_delete_rejected","idempotent_retry","shipping_concurrency_two_connections"])expect(sql).toContain(value);expect(sql.toLowerCase()).toContain("rollback;");});
});
