import { notFound } from "next/navigation";
import { PaymentActions,PaymentForm } from "@/components/sales/sales-forms";
import { OperationalStatusBadge } from "@/components/inventory/inventory-ui";
import { Feedback,PageHeader,SectionCard,formatPEN } from "@/components/ui/operational-ui";
import { requireActiveUser } from "@/lib/auth/session";
import { getPayment,listOrderOptions } from "@/services/sales";
import { salesIdSchema } from "@/validations/sales";
import { paymentMethodLabels,paymentStatusLabels } from "@/features/sales/domain";
export default async function Page({params}:{params:Promise<{id:string}>}){const user=await requireActiveUser();const parsed=salesIdSchema.safeParse((await params).id);if(!parsed.success)notFound();const [payment,orders]=await Promise.all([getPayment(parsed.data),listOrderOptions()]);if(!payment)notFound();return <section className="max-w-5xl"><PageHeader title={payment.paymentNumber} description={`${payment.orderNumber} · ${paymentMethodLabels[payment.method]}`} backHref="/app/pagos" backLabel="Volver a pagos" action={<OperationalStatusBadge label={paymentStatusLabels[payment.status]}/>}/><div className="grid gap-5 lg:grid-cols-[minmax(0,1fr)_18rem]"><div className="space-y-5">{payment.refundedPaymentId?<Feedback tone="info">Este registro corresponde a un reembolso asociado y conserva la trazabilidad del pago original.</Feedback>:null}{payment.status==="pending"?<SectionCard title="Editar pago pendiente"><PaymentForm payment={payment} orders={orders}/></SectionCard>:<SectionCard title="Información del pago"><dl className="grid gap-4 sm:grid-cols-2"><Item label="Pedido" value={payment.orderNumber}/><Item label="Método" value={paymentMethodLabels[payment.method]}/><Item label="Referencia" value={payment.reference??"—"}/><Item label="Estado" value={paymentStatusLabels[payment.status]}/></dl></SectionCard>}<PaymentActions payment={payment} isAdmin={user.role==="administrator"}/></div><aside><SectionCard title="Resumen"><p className="text-sm text-slate-500">Importe registrado</p><p className="mt-1 text-2xl font-bold tabular-nums text-slate-950">{formatPEN(payment.amount)}</p></SectionCard></aside></div></section>}
function Item({label,value}:{label:string;value:string}){return <div><dt className="text-xs font-medium uppercase tracking-wide text-slate-500">{label}</dt><dd className="mt-1 font-medium text-slate-900">{value}</dd></div>}
