import { notFound } from "next/navigation";
import { OrderActions,OrderForm,OrderItemActions,OrderItemForm } from "@/components/sales/sales-forms";
import { OperationalStatusBadge } from "@/components/inventory/inventory-ui";
import { PageHeader,SectionCard,formatPEN } from "@/components/ui/operational-ui";
import { requireActiveUser } from "@/lib/auth/session";
import { getOrder,listBalanceOptions,listCustomerOptions,listReturnLocationOptions } from "@/services/sales";
import { salesIdSchema } from "@/validations/sales";
import { orderPaymentLabels,orderStatusLabels } from "@/features/sales/domain";

export default async function Page({params}:{params:Promise<{id:string}>}){await requireActiveUser();const parsed=salesIdSchema.safeParse((await params).id);if(!parsed.success)notFound();const [order,customers,balances,returnLocations]=await Promise.all([getOrder(parsed.data),listCustomerOptions(),listBalanceOptions(),listReturnLocationOptions()]);if(!order)notFound();return <section><PageHeader title={order.orderNumber} description={order.customerName} backHref="/app/pedidos" backLabel="Volver a pedidos" action={<div className="flex flex-wrap items-center justify-end gap-2"><OperationalStatusBadge label={orderStatusLabels[order.status]}/><OrderActions order={order}/></div>}/><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_20rem]"><div className="min-w-0 space-y-5">{order.status==="draft"?<><SectionCard title="Datos del pedido" description="Editable mientras permanezca en borrador."><OrderForm order={order} customers={customers}/></SectionCard><SectionCard title="Añadir línea" description="Selecciona el balance exacto que se reservará al confirmar."><OrderItemForm orderId={order.id} balances={balances}/></SectionCard></>:null}<section><div className="mb-3 flex items-center justify-between"><h2 className="text-lg font-semibold text-slate-950">Líneas del pedido</h2><span className="text-sm text-slate-500">{order.items.length} registros</span></div><div className="space-y-3">{order.items.map((item)=><article key={item.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm sm:p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="text-xs font-semibold text-emerald-700">Línea {item.lineNumber}</p><h3 className="font-semibold text-slate-950">{item.variantLabel}</h3></div><strong className="tabular-nums">{formatPEN(item.lineTotal)}</strong></div><p className="mt-2 text-sm text-slate-500">{item.locationLabel}</p><dl className="mt-4 grid grid-cols-2 gap-3 text-sm sm:grid-cols-4"><Value label="Cantidad" value={item.quantity}/><Value label="Reservada" value={item.reservedQuantity}/><Value label="Despachada" value={item.dispatchedQuantity}/><Value label="Devuelta" value={item.returnedQuantity}/></dl>{order.status!=="draft"?<p className="mt-3 text-xs text-slate-500">Costo histórico: {formatPEN(item.unitCostSnapshot)}</p>:null}<div className="mt-4 border-t border-slate-100 pt-3"><OrderItemActions item={item} returnLocations={returnLocations}/></div></article>)}</div></section></div><aside className="xl:sticky xl:top-22 xl:self-start"><SectionCard title="Resumen"><dl className="space-y-3 text-sm"><Summary label="Estado" value={orderStatusLabels[order.status]}/><Summary label="Estado de pago" value={orderPaymentLabels[order.paymentStatus]}/><Summary label="Total" value={formatPEN(order.totalAmount)} strong/><Summary label="Saldo pendiente" value={formatPEN(order.balanceDue)} strong/></dl></SectionCard></aside></div></section>}
function Value({label,value}:{label:string;value:number}){return <div className="rounded-lg bg-slate-50 p-2.5"><dt className="text-xs text-slate-500">{label}</dt><dd className="mt-1 font-semibold tabular-nums">{value}</dd></div>}
function Summary({label,value,strong=false}:{label:string;value:string;strong?:boolean}){return <div className="flex items-center justify-between gap-4"><dt className="text-slate-500">{label}</dt><dd className={strong?"font-bold text-slate-950":"font-medium text-slate-800"}>{value}</dd></div>}
