import Link from "next/link";
import { CatalogFiltersForm, Pagination, StatusBadge } from "@/components/catalogs/catalog-ui";
import { parseCatalogFilters } from "@/features/catalogs/filters";
import { canManageCatalogs } from "@/features/catalogs/permissions";
import { requireActiveUser } from "@/lib/auth/session";
import { listWarehouses } from "@/services/catalogs";
import { EmptyState, Feedback, PageHeader, ResponsiveList, buttonStyles, tableCellClass, tableClass, tableHeadClass, tableRowClass } from "@/components/ui/operational-ui";
import { Icon } from "@/components/ui/icons";

export default async function WarehousesPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const user=await requireActiveUser();const isAdministrator=canManageCatalogs(user.role);const filters=parseCatalogFilters(await searchParams);let result;try{result=await listWarehouses(filters,isAdministrator);}catch{return <Feedback tone="warning"><strong>Almacenes.</strong> No fue posible cargar la información solicitada.</Feedback>;}const action=isAdministrator?<Link href="/app/almacenes/nuevo" className={buttonStyles.primary}><Icon name="plus" className="size-4"/>Crear almacén</Link>:undefined;return <section><PageHeader title="Almacenes" description="Espacios operativos y ubicaciones internas de inventario." action={action}/><CatalogFiltersForm basePath="/app/almacenes" filters={filters} isAdministrator={isAdministrator} placeholder="Código o nombre"/>{result.items.length?<ResponsiveList table={<table className={tableClass}><thead className={tableHeadClass}><tr><th className={tableCellClass}>Código</th><th className={tableCellClass}>Almacén</th><th className={tableCellClass}>Descripción</th><th className={tableCellClass}>Estado</th><th className={`${tableCellClass} text-right`}>Acción</th></tr></thead><tbody>{result.items.map((item)=><tr key={item.id} className={tableRowClass}><td className={`${tableCellClass} font-mono text-xs font-semibold text-emerald-700`}>{item.code}</td><td className={`${tableCellClass} font-semibold`}>{item.name}</td><td className={`${tableCellClass} max-w-sm truncate text-slate-600`}>{item.description??"—"}</td><td className={tableCellClass}><StatusBadge active={item.isActive}/></td><td className={`${tableCellClass} text-right`}><Link href={`/app/almacenes/${item.id}`} className="font-semibold text-emerald-700">Ver detalle</Link></td></tr>)}</tbody></table>} cards={result.items.map((item)=><Link key={item.id} href={`/app/almacenes/${item.id}`} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><div><p className="font-mono text-xs font-semibold text-emerald-700">{item.code}</p><h2 className="mt-1 font-semibold">{item.name}</h2></div><StatusBadge active={item.isActive}/></div><p className="mt-3 line-clamp-2 text-sm text-slate-500">{item.description??"Sin descripción."}</p></Link>)}/>:<EmptyState title="No hay almacenes" description="No se encontraron almacenes con los filtros seleccionados." action={action} icon="warehouses"/>}<Pagination basePath="/app/almacenes" page={result.page} pageCount={result.pageCount} query={filters.query} status={filters.status}/></section>}
