import Link from "next/link";
import { OperationalPagination,OperationalStatusBadge } from "@/components/inventory/inventory-ui";
import { EmptyState,FilterBar,PageHeader,ResponsiveList,buttonStyles,fieldClass,formatLimaDate,formatPEN,tableCellClass,tableClass,tableHeadClass,tableRowClass } from "@/components/ui/operational-ui";
import { Icon } from "@/components/ui/icons";
import { shipmentStatusLabels } from "@/features/shipping/domain";
import { parseShippingFilters } from "@/features/shipping/filters";
import { requireActiveUser } from "@/lib/auth/session";
import { listShipments } from "@/services/shipping";
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){await requireActiveUser();const filters=parseShippingFilters(await searchParams);const result=await listShipments(filters);const action=<Link href="/app/envios/nuevo" className={buttonStyles.primary}><Icon name="plus" className="size-4"/>Nuevo envío</Link>;return <section><PageHeader title="Envíos" description="Preparación, entrega al transportista y trazabilidad logística." action={action}/><form><FilterBar className="grid gap-3 sm:grid-cols-[1fr_13rem_auto] sm:items-end"><label className="text-sm font-medium">Buscar<input name="query" defaultValue={filters.query} placeholder="Envío o seguimiento" className={fieldClass}/></label><label className="text-sm font-medium">Estado<select name="status" defaultValue={filters.status} className={fieldClass}><option value="all">Todos</option>{Object.entries(shipmentStatusLabels).map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label><button className={buttonStyles.primary}>Aplicar</button></FilterBar></form>{result.items.length?<ResponsiveList table={<table className={tableClass}><thead className={tableHeadClass}><tr><th className={tableCellClass}>Envío</th><th className={tableCellClass}>Pedido</th><th className={tableCellClass}>Cliente</th><th className={tableCellClass}>Estado</th><th className={tableCellClass}>Costo</th><th className={tableCellClass}>Fecha</th></tr></thead><tbody>{result.items.map(v=><tr key={v.id} className={tableRowClass}><td className={`${tableCellClass} font-semibold`}><Link href={`/app/envios/${v.id}`} className="text-[var(--app-primary)]">{v.shipmentNumber}</Link></td><td className={tableCellClass}>{v.orderNumber}</td><td className={tableCellClass}>{v.customerName}</td><td className={tableCellClass}><OperationalStatusBadge label={shipmentStatusLabels[v.status]}/></td><td className={tableCellClass}>{formatPEN(v.shippingCost)}</td><td className={tableCellClass}>{formatLimaDate(v.createdAt,true)}</td></tr>)}</tbody></table>} cards={result.items.map(v=><Link key={v.id} href={`/app/envios/${v.id}`} className="app-surface rounded-xl border p-4 shadow-sm"><div className="flex justify-between gap-3"><strong>{v.shipmentNumber}</strong><OperationalStatusBadge label={shipmentStatusLabels[v.status]}/></div><p className="app-muted mt-2 text-sm">{v.orderNumber} · {v.customerName}</p><p className="mt-3 text-sm font-semibold">{formatPEN(v.shippingCost)}</p></Link>)}/>:<EmptyState title="No hay envíos" description="No se encontraron envíos con estos filtros." action={action} icon="shipments"/>}<OperationalPagination basePath="/app/envios" page={result.page} pageCount={result.pageCount} params={{query:filters.query,status:filters.status}}/></section>}
