import Link from "next/link";
import { CarrierStatusButton,ShippingReconciliationButton } from "@/components/shipping/shipping-forms";
import { EmptyState,FilterBar,PageHeader,ResponsiveList,StatusBadge,buttonStyles,fieldClass,tableCellClass,tableClass,tableHeadClass,tableRowClass } from "@/components/ui/operational-ui";
import { Icon } from "@/components/ui/icons";
import { OperationalPagination } from "@/components/inventory/inventory-ui";
import { parseShippingFilters } from "@/features/shipping/filters";
import { requireAdministrator } from "@/lib/auth/session";
import { listCarriers } from "@/services/shipping";
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){await requireAdministrator();const filters=parseShippingFilters(await searchParams);const result=await listCarriers(filters);const action=<div className="flex flex-wrap gap-2"><ShippingReconciliationButton/><Link href="/app/transportistas/nuevo" className={buttonStyles.primary}><Icon name="plus" className="size-4"/>Nuevo transportista</Link></div>;return <section><PageHeader title="Transportistas" description="Catálogo privado para la operación logística." action={action}/><form><FilterBar className="grid gap-3 sm:grid-cols-[1fr_12rem_auto] sm:items-end"><label className="text-sm font-medium">Buscar<input name="query" defaultValue={filters.query} placeholder="Código o nombre" className={fieldClass}/></label><label className="text-sm font-medium">Estado<select name="status" defaultValue={filters.status} className={fieldClass}><option value="all">Todos</option><option value="active">Activos</option><option value="inactive">Inactivos</option></select></label><button className={buttonStyles.primary}>Aplicar</button></FilterBar></form>{result.items.length?<ResponsiveList table={<table className={tableClass}><thead className={tableHeadClass}><tr><th className={tableCellClass}>Código</th><th className={tableCellClass}>Nombre</th><th className={tableCellClass}>Estado</th><th className={tableCellClass}>Acciones</th></tr></thead><tbody>{result.items.map(v=><tr key={v.id} className={tableRowClass}><td className={tableCellClass}>{v.code}</td><td className={tableCellClass}><Link className="font-semibold text-[var(--app-primary)]" href={`/app/transportistas/${v.id}`}>{v.name}</Link></td><td className={tableCellClass}><StatusBadge label={v.isActive?"Activo":"Inactivo"} tone={v.isActive?"success":"neutral"}/></td><td className={tableCellClass}><CarrierStatusButton carrier={v}/></td></tr>)}</tbody></table>} cards={result.items.map(v=><article key={v.id} className="app-surface rounded-xl border p-4"><div className="flex justify-between"><Link href={`/app/transportistas/${v.id}`} className="font-semibold">{v.code} · {v.name}</Link><StatusBadge label={v.isActive?"Activo":"Inactivo"} tone={v.isActive?"success":"neutral"}/></div><div className="mt-3"><CarrierStatusButton carrier={v}/></div></article>)}/>:<EmptyState title="No hay transportistas" description="No se encontraron transportistas." action={action} icon="carriers"/>}<OperationalPagination basePath="/app/transportistas" page={result.page} pageCount={result.pageCount} params={{query:filters.query,status:filters.status}}/></section>}
