import Link from "next/link";
import { CatalogFiltersForm, Pagination, StatusBadge } from "@/components/catalogs/catalog-ui";
import { parseCatalogFilters } from "@/features/catalogs/filters";
import { canManageCatalogs } from "@/features/catalogs/permissions";
import { requireActiveUser } from "@/lib/auth/session";
import { listProducts } from "@/services/catalogs";
import { EmptyState, Feedback, PageHeader, ResponsiveList, buttonStyles, tableCellClass, tableClass, tableHeadClass, tableRowClass } from "@/components/ui/operational-ui";
import { Icon } from "@/components/ui/icons";

export default async function ProductsPage({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  const user=await requireActiveUser();const isAdministrator=canManageCatalogs(user.role);const filters=parseCatalogFilters(await searchParams);let result;try{result=await listProducts(filters,isAdministrator);}catch{return <Feedback tone="warning"><strong>Productos.</strong> No fue posible cargar la información solicitada.</Feedback>;}
  const action=isAdministrator?<Link href="/app/productos/nuevo" className={buttonStyles.primary}><Icon name="plus" className="size-4"/>Crear producto</Link>:undefined;
  return <section><PageHeader title="Productos" description="Productos comerciales, variantes vendibles, SKU y precios." action={action}/><CatalogFiltersForm basePath="/app/productos" filters={filters} isAdministrator={isAdministrator} placeholder="Nombre, SKU, marca, categoría o color"/>{result.items.length?<ResponsiveList table={<table className={tableClass}><thead className={tableHeadClass}><tr><th className={tableCellClass}>Producto</th><th className={tableCellClass}>Marca</th><th className={tableCellClass}>Categoría</th><th className={tableCellClass}>Unidad</th><th className={tableCellClass}>Estado</th><th className={`${tableCellClass} text-right`}>Acción</th></tr></thead><tbody>{result.items.map((item)=><tr key={item.id} className={tableRowClass}><td className={`${tableCellClass} font-semibold text-slate-950`}>{item.name}</td><td className={tableCellClass}>{item.brand??"—"}</td><td className={tableCellClass}>{item.category??"—"}</td><td className={tableCellClass}>{item.unitCode}</td><td className={tableCellClass}><StatusBadge active={item.isActive}/></td><td className={`${tableCellClass} text-right`}><Link href={`/app/productos/${item.id}`} className="font-semibold text-emerald-700">Ver detalle</Link></td></tr>)}</tbody></table>} cards={result.items.map((item)=><Link key={item.id} href={`/app/productos/${item.id}`} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><h2 className="font-semibold text-slate-950">{item.name}</h2><StatusBadge active={item.isActive}/></div><dl className="mt-3 grid grid-cols-2 gap-2 text-sm"><div><dt className="text-xs text-slate-500">Marca</dt><dd>{item.brand??"—"}</dd></div><div><dt className="text-xs text-slate-500">Categoría</dt><dd>{item.category??"—"}</dd></div></dl></Link>)}/>:<EmptyState title="No hay productos" description="No se encontraron productos con los filtros seleccionados." action={action} icon="products"/>}<Pagination basePath="/app/productos" page={result.page} pageCount={result.pageCount} query={filters.query} status={filters.status}/></section>;
}
