import Link from "next/link";
import { CatalogFiltersForm, Pagination, StatusBadge } from "@/components/catalogs/catalog-ui";
import { parseCatalogFilters } from "@/features/catalogs/filters";
import { canManageCatalogs } from "@/features/catalogs/permissions";
import { requireActiveUser } from "@/lib/auth/session";
import { listSuppliers } from "@/services/catalogs";
import { EmptyState, Feedback, PageHeader, ResponsiveList, buttonStyles, tableCellClass, tableClass, tableHeadClass, tableRowClass } from "@/components/ui/operational-ui";
import { Icon } from "@/components/ui/icons";

export default async function SuppliersPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const user=await requireActiveUser();const isAdministrator=canManageCatalogs(user.role);const filters=parseCatalogFilters(await searchParams);let result;try{result=await listSuppliers(filters,isAdministrator);}catch{return <Feedback tone="warning"><strong>Proveedores.</strong> No fue posible cargar la información solicitada.</Feedback>;}const action=isAdministrator?<Link href="/app/proveedores/nuevo" className={buttonStyles.primary}><Icon name="plus" className="size-4"/>Crear proveedor</Link>:undefined;return <section><PageHeader title="Proveedores" description="Directorio privado de abastecimiento y compras." action={action}/><CatalogFiltersForm basePath="/app/proveedores" filters={filters} isAdministrator={isAdministrator} placeholder="Código o razón social"/>{result.items.length?<ResponsiveList table={<table className={tableClass}><thead className={tableHeadClass}><tr><th className={tableCellClass}>Código</th><th className={tableCellClass}>Razón social</th><th className={tableCellClass}>Estado</th><th className={`${tableCellClass} text-right`}>Acción</th></tr></thead><tbody>{result.items.map((item)=><tr key={item.id} className={tableRowClass}><td className={`${tableCellClass} font-mono text-xs font-semibold text-emerald-700`}>{item.code}</td><td className={`${tableCellClass} font-semibold`}>{item.businessName}</td><td className={tableCellClass}><StatusBadge active={item.isActive}/></td><td className={`${tableCellClass} text-right`}><Link href={`/app/proveedores/${item.id}`} className="font-semibold text-emerald-700">Ver detalle</Link></td></tr>)}</tbody></table>} cards={result.items.map((item)=><Link key={item.id} href={`/app/proveedores/${item.id}`} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex justify-between gap-3"><div><p className="font-mono text-xs font-semibold text-emerald-700">{item.code}</p><h2 className="mt-1 font-semibold">{item.businessName}</h2></div><StatusBadge active={item.isActive}/></div></Link>)}/>:<EmptyState title="No hay proveedores" description="No se encontraron proveedores con los filtros seleccionados." action={action} icon="suppliers"/>}<Pagination basePath="/app/proveedores" page={result.page} pageCount={result.pageCount} query={filters.query} status={filters.status}/></section>}
