import { notFound } from "next/navigation";
import { ShipmentActions,ShipmentItemForm,RemoveShipmentItemButton } from "@/components/shipping/shipping-forms";
import { OperationalStatusBadge } from "@/components/inventory/inventory-ui";
import { PageHeader,SectionCard,formatLimaDate,formatPEN } from "@/components/ui/operational-ui";
import { shipmentEventLabels,shipmentStatusLabels } from "@/features/shipping/domain";
import { requireActiveUser } from "@/lib/auth/session";
import { getShipment,listShippableItemOptions } from "@/services/shipping";
import { shippingIdSchema } from "@/validations/shipping";
export default async function Page({params}:{params:Promise<{id:string}>}){const user=await requireActiveUser();const parsed=shippingIdSchema.safeParse((await params).id);if(!parsed.success)notFound();const shipment=await getShipment(parsed.data);if(!shipment)notFound();const options=shipment.status==="draft"?await listShippableItemOptions(shipment.orderId):[];return <section><PageHeader title={shipment.shipmentNumber} description={`${shipment.orderNumber} · ${shipment.customerName}`} backHref="/app/envios" action={<><OperationalStatusBadge label={shipmentStatusLabels[shipment.status]}/><ShipmentActions shipment={shipment} isAdmin={user.role==="administrator"}/></>}/><div className="grid gap-5 xl:grid-cols-[minmax(0,1fr)_22rem]"><div className="space-y-5">{shipment.status==="draft"?<SectionCard title="Añadir línea" description="Solo cantidades previamente despachadas y aún no asignadas."><ShipmentItemForm shipmentId={shipment.id} items={options}/></SectionCard>:null}<SectionCard title="Contenido" description={`${shipment.items.length} líneas asignadas.`}><div className="space-y-3">{shipment.items.map(v=><article key={v.id} className="app-soft rounded-lg p-3"><div className="flex flex-wrap items-center justify-between gap-3"><div><strong>{v.variantLabel}</strong><p className="app-muted text-sm">Cantidad: {v.quantity}</p></div>{shipment.status==="draft"?<RemoveShipmentItemButton item={v}/>:null}</div></article>)}</div></SectionCard><SectionCard title="Seguimiento" description="Línea de tiempo inmutable de eventos logísticos."><ol className="relative ml-2 border-l border-[var(--app-border)] pl-6">{shipment.events.map(v=><li key={v.id} className="relative pb-6 last:pb-0"><span className="absolute -left-[1.82rem] top-1 size-3 rounded-full bg-[var(--app-primary-solid)]"/><p className="font-semibold">{shipmentEventLabels[v.eventType]}</p><p className="app-muted text-xs">{formatLimaDate(v.occurredAt,true)}{v.location?` · ${v.location}`:""}</p>{v.description?<p className="mt-1 text-sm">{v.description}</p>:null}</li>)}</ol></SectionCard></div><aside className="space-y-5 xl:sticky xl:top-22 xl:self-start"><SectionCard title="Destinatario"><dl className="space-y-3 text-sm"><Value label="Nombre" value={shipment.recipientName}/><Value label="Teléfono" value={shipment.recipientPhone??"No registrado"}/><Value label="Dirección" value={[shipment.addressLine,shipment.district,shipment.province,shipment.department].filter(Boolean).join(", ")}/><Value label="Referencia" value={shipment.addressReference??"No registrada"}/></dl></SectionCard><SectionCard title="Logística"><dl className="space-y-3 text-sm"><Value label="Transportista" value={shipment.carrierName??"Sin asignar"}/><Value label="Seguimiento" value={shipment.trackingNumber??"Sin asignar"}/><Value label="Costo" value={formatPEN(shipment.shippingCost)}/><Value label="Versión" value={String(shipment.version)}/></dl></SectionCard></aside></div></section>}
function Value({label,value}:{label:string;value:string}){return <div><dt className="app-muted text-xs">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>}
