"use server";
import { revalidatePath } from "next/cache";
import type { ActionResult } from "@/app/actions/auth";
import { limaDateTimeLocalToUtc } from "@/features/inventory/lima-time";
import { getCurrentUserContext } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { customerSchema,orderItemSchema,orderSchema,paidAtSchema,paymentSchema,quantityOperationSchema,refundSchema,returnOperationSchema,salesIdSchema } from "@/validations/sales";

const fail=(message="Revisa los datos ingresados."):ActionResult=>({ok:false,message});
async function client(admin=false){const user=await getCurrentUserContext();if(!user||!(["administrator","operator"] as string[]).includes(user.role)||(admin&&user.role!=="administrator"))return null;return {supabase:await createClient(),user};}
const safe=(error:{code?:string;message:string},fallback:string)=>error.code==="PGRST116"||error.code==="P0002"||error.code==="42501"?"Registro no encontrado o no autorizado.":error.code==="23505"?"Ya existe un registro con esos datos.":error.message.toLowerCase().includes("stock")||error.message.toLowerCase().includes("reserva")?"No existe stock disponible suficiente.":error.message.toLowerCase().includes("estado")||error.message.toLowerCase().includes("borrador")||error.message.toLowerCase().includes("confirm")?"El estado actual no permite esta operación.":fallback;
const refresh=(id?:string)=>{revalidatePath("/app/clientes");revalidatePath("/app/pedidos");revalidatePath("/app/pagos");revalidatePath("/app/inventario");if(id)revalidatePath(`/app/pedidos/${id}`);};

export async function checkCustomerDuplicatesAction(input:unknown):Promise<ActionResult>{const p=customerSchema.safeParse(input);if(!p.success)return fail(p.error.issues[0]?.message);const c=await client();if(!c)return fail("Acción no autorizada.");const {data,error}=await c.supabase.rpc("check_customer_duplicate_candidates",{p_document_type:p.data.documentType,p_document_number:p.data.documentNumber,p_email:p.data.email,p_phone:p.data.phone,p_full_name:p.data.fullName});if(error)return fail(safe(error,"No fue posible revisar posibles duplicados."));const match=data[0];const exact=Boolean(match?.document_match||match?.email_match||match?.phone_match),name=Boolean(match?.name_match);return{ok:true,message:exact?"Se encontraron coincidencias exactas. Revisa la búsqueda antes de crear.":name?"Existe un nombre coincidente; revisa antes de crear.":"No se encontraron coincidencias."};}

export async function saveCustomerAction(id:string|null,input:unknown):Promise<ActionResult>{const p=customerSchema.safeParse(input),pid=id?salesIdSchema.safeParse(id):null;if(!p.success)return fail(p.error.issues[0]?.message);if(pid&&!pid.success)return fail(pid.error.issues[0]?.message);const c=await client();if(!c)return fail("Acción no autorizada.");const values={full_name:p.data.fullName,document_type:p.data.documentType,document_number:p.data.documentNumber,email:p.data.email,phone:p.data.phone,address:p.data.address,notes:p.data.notes};const r=pid?await c.supabase.from("customers").update(values).eq("id",pid.data).select("id").single():await c.supabase.from("customers").insert(values).select("id").single();if(r.error)return fail(safe(r.error,"No fue posible guardar el cliente."));refresh();return{ok:true,message:pid?"Cliente actualizado.":"Cliente creado.",redirectTo:`/app/clientes/${r.data.id}`};}
export async function setCustomerStatusAction(id:unknown,active:unknown):Promise<ActionResult>{const p=salesIdSchema.safeParse(id);if(!p.success||typeof active!=="boolean")return fail();const c=await client(true);if(!c)return fail("Acción reservada para administradores activos.");const r=await c.supabase.from("customers").update({is_active:active}).eq("id",p.data).select("id").single();if(r.error)return fail(safe(r.error,"No fue posible cambiar el estado."));refresh();return{ok:true,message:active?"Cliente activado.":"Cliente desactivado."};}
export async function saveOrderAction(id:string|null,input:unknown):Promise<ActionResult>{const p=orderSchema.safeParse(input),pid=id?salesIdSchema.safeParse(id):null;if(!p.success)return fail(p.error.issues[0]?.message);if(pid&&!pid.success)return fail();const instant=limaDateTimeLocalToUtc(p.data.orderedAt);if(!instant)return fail("Fecha inválida.");const c=await client();if(!c)return fail("Acción no autorizada.");const values={customer_id:p.data.customerId,ordered_at:instant,notes:p.data.notes};const r=pid?await c.supabase.from("orders").update(values).eq("id",pid.data).select("id").single():await c.supabase.from("orders").insert(values).select("id").single();if(r.error)return fail(safe(r.error,"No fue posible guardar el pedido."));refresh(r.data.id);return{ok:true,message:pid?"Pedido actualizado.":"Pedido creado.",redirectTo:`/app/pedidos/${r.data.id}`};}
export async function saveOrderItemAction(id:string|null,input:unknown):Promise<ActionResult>{const p=orderItemSchema.safeParse(input),pid=id?salesIdSchema.safeParse(id):null;if(!p.success)return fail(p.error.issues[0]?.message);const c=await client();if(!c)return fail("Acción no autorizada.");const values={line_number:p.data.lineNumber,variant_id:p.data.variantId,warehouse_id:p.data.warehouseId,location_id:p.data.locationId,quantity:p.data.quantity,unit_price:p.data.unitPrice,discount_amount:p.data.discountAmount,tax_amount:p.data.taxAmount};const r=pid?.success?await c.supabase.from("order_items").update(values).eq("id",pid.data).select("id,order_id").single():await c.supabase.from("order_items").insert({...values,order_id:p.data.orderId}).select("id,order_id").single();if(r.error)return fail(safe(r.error,"No fue posible guardar la línea."));refresh(r.data.order_id);return{ok:true,message:"Línea guardada."};}
export async function removeOrderItemAction(id:unknown):Promise<ActionResult>{const p=salesIdSchema.safeParse(id),c=await client();if(!p.success||!c)return fail("Acción no autorizada.");const {data,error}=await c.supabase.rpc("remove_order_item",{p_order_item_id:p.data});if(error||!data)return fail(safe(error??{message:"no rows"},"No fue posible retirar la línea."));refresh(data);return{ok:true,message:"Línea retirada."};}

type SimpleRpc="submit_order"|"return_order_to_draft"|"deliver_order";
async function simpleOrderRpc(name:SimpleRpc,id:unknown,message:string){const p=salesIdSchema.safeParse(id),c=await client();if(!p.success||!c)return fail("Acción no autorizada.");const {data,error}=await c.supabase.rpc(name,{p_order_id:p.data});if(error||!data)return fail(safe(error??{message:"no rows"},"No fue posible cambiar el pedido."));refresh(p.data);return{ok:true,message} satisfies ActionResult;}
export async function submitOrderAction(id:unknown){return simpleOrderRpc("submit_order",id,"Pedido enviado.");}
export async function returnOrderToDraftAction(id:unknown){return simpleOrderRpc("return_order_to_draft",id,"Pedido devuelto a borrador.");}
export async function deliverOrderAction(id:unknown){return simpleOrderRpc("deliver_order",id,"Pedido entregado.");}
async function keyedOrderRpc(name:"confirm_order"|"cancel_order"|"dispatch_order",id:unknown,key:unknown,message:string){const p=salesIdSchema.safeParse(id),k=salesIdSchema.safeParse(key),c=await client();if(!p.success||!k.success||!c)return fail("Operación inválida.");const {data,error}=await c.supabase.rpc(name,{p_order_id:p.data,p_idempotency_key:k.data});if(error||!data)return fail(safe(error??{message:"no rows"},"No fue posible procesar el pedido."));refresh(p.data);return{ok:true,message} satisfies ActionResult;}
export async function confirmOrderAction(id:unknown,key:unknown){return keyedOrderRpc("confirm_order",id,key,"Pedido confirmado y stock reservado.");}
export async function cancelOrderAction(id:unknown,key:unknown){return keyedOrderRpc("cancel_order",id,key,"Pedido cancelado y reserva liberada.");}
export async function dispatchOrderAction(id:unknown,key:unknown){return keyedOrderRpc("dispatch_order",id,key,"Pedido despachado.");}
export async function dispatchOrderItemAction(input:unknown){const p=quantityOperationSchema.safeParse(input),c=await client();if(!p.success||!c)return fail(p.success?"Acción no autorizada.":p.error.issues[0]?.message);const {data,error}=await c.supabase.rpc("dispatch_order_item",{p_order_item_id:p.data.itemId,p_quantity:p.data.quantity,p_idempotency_key:p.data.idempotencyKey});if(error||!data)return fail(safe(error??{message:"no rows"},"No fue posible despachar."));refresh();return{ok:true,message:"Despacho registrado."} satisfies ActionResult;}
export async function returnOrderItemAction(input:unknown){const p=returnOperationSchema.safeParse(input),c=await client();if(!p.success||!c)return fail(p.success?"Acción no autorizada.":p.error.issues[0]?.message);const {data,error}=await c.supabase.rpc("return_order_item",{p_order_item_id:p.data.itemId,p_location_id:p.data.locationId,p_quantity:p.data.quantity,p_reason:p.data.reason,p_idempotency_key:p.data.idempotencyKey});if(error||!data)return fail(safe(error??{message:"no rows"},"No fue posible devolver la línea."));refresh();return{ok:true,message:"Devolución registrada."} satisfies ActionResult;}
export async function savePaymentAction(id:string|null,input:unknown):Promise<ActionResult>{const p=paymentSchema.safeParse(input),pid=id?salesIdSchema.safeParse(id):null;if(!p.success)return fail(p.error.issues[0]?.message);const c=await client();if(!c)return fail("Acción no autorizada.");const values={order_id:p.data.orderId,amount:p.data.amount,method:p.data.method,reference:p.data.reference,notes:p.data.notes};const r=pid?.success?await c.supabase.from("payments").update(values).eq("id",pid.data).select("id").single():await c.supabase.from("payments").insert(values).select("id").single();if(r.error)return fail(safe(r.error,"No fue posible guardar el pago."));refresh();return{ok:true,message:"Pago pendiente guardado.",redirectTo:`/app/pagos/${r.data.id}`};}
export async function confirmPaymentAction(input:unknown){const p=paidAtSchema.safeParse(input),c=await client();if(!p.success||!c)return fail(p.success?"Acción no autorizada.":p.error.issues[0]?.message);const paidAt=limaDateTimeLocalToUtc(p.data.paidAt);if(!paidAt)return fail("Fecha inválida.");const {data,error}=await c.supabase.rpc("confirm_payment",{p_payment_id:p.data.paymentId,p_paid_at:paidAt,p_idempotency_key:p.data.idempotencyKey});if(error||!data)return fail(safe(error??{message:"no rows"},"No fue posible confirmar el pago."));refresh();return{ok:true,message:"Pago confirmado."} satisfies ActionResult;}
export async function cancelPaymentAction(id:unknown){const p=salesIdSchema.safeParse(id),c=await client();if(!p.success||!c)return fail("Acción no autorizada.");const {data,error}=await c.supabase.rpc("cancel_payment",{p_payment_id:p.data});if(error||!data)return fail(safe(error??{message:"no rows"},"No fue posible cancelar el pago."));refresh();return{ok:true,message:"Pago cancelado."} satisfies ActionResult;}
export async function refundPaymentAction(input:unknown){const p=refundSchema.safeParse(input),c=await client(true);if(!p.success||!c)return fail(p.success?"Acción reservada para administradores activos.":p.error.issues[0]?.message);const {data,error}=await c.supabase.rpc("refund_payment",{p_payment_id:p.data.paymentId,p_amount:p.data.amount,p_reason:p.data.reason,p_idempotency_key:p.data.idempotencyKey});if(error||!data)return fail(safe(error??{message:"no rows"},"No fue posible reembolsar el pago."));refresh();return{ok:true,message:"Reembolso registrado sin modificar el pago original."} satisfies ActionResult;}
export async function runFinancialReconciliationAction():Promise<ActionResult>{const c=await client(true);if(!c)return fail("Acción reservada para administradores activos.");const {data,error}=await c.supabase.rpc("admin_financial_reconciliation",{});if(error)return fail(safe(error,"No fue posible conciliar los pagos."));return{ok:true,message:data.length?`Conciliación completada: ${data.length} diferencia(s).`:"Conciliación completada sin diferencias."};}
