"use server";
import { revalidatePath } from "next/cache";
import type { ActionResult } from "@/app/actions/auth";
import { getCurrentUserContext } from "@/lib/auth/session";
import { createClient } from "@/lib/supabase/server";
import { carrierSchema,deliveryAttemptSchema,shipmentItemSchema,shipmentSchema,shipmentTransitionSchema,shippingIdSchema } from "@/validations/shipping";
const fail=(message="Revisa los datos ingresados."):ActionResult=>({ok:false,message});
async function context(admin=false){const user=await getCurrentUserContext();if(!user||!(user.role==="administrator"||user.role==="operator")||(admin&&user.role!=="administrator"))return null;return{user,supabase:await createClient()};}
const safe=(error:{code?:string;message:string},fallback:string)=>error.code==="PGRST116"||error.code==="P0002"||error.code==="42501"?"Registro no encontrado o no autorizado.":error.code==="23505"?"Ya existe un registro con esos datos.":error.message.toLowerCase().includes("estado")?"El estado actual no permite esta operación.":error.message.toLowerCase().includes("cantidad")?"La cantidad supera lo disponible para enviar.":fallback;
const refresh=(id?:string)=>{revalidatePath("/app/envios");revalidatePath("/app/transportistas");if(id)revalidatePath(`/app/envios/${id}`);};
export async function saveCarrierAction(id:string|null,input:unknown):Promise<ActionResult>{const parsed=carrierSchema.safeParse(input),pid=id?shippingIdSchema.safeParse(id):null;if(!parsed.success)return fail(parsed.error.issues[0]?.message);if(pid&&!pid.success)return fail();const c=await context(true);if(!c)return fail("Acción reservada para administradores activos.");const value={code:parsed.data.code,name:parsed.data.name,contact_name:parsed.data.contactName,email:parsed.data.email,phone:parsed.data.phone,tracking_url_template:parsed.data.trackingUrlTemplate,notes:parsed.data.notes};const result=pid?await c.supabase.from("carriers").update(value).eq("id",pid.data).select("id").single():await c.supabase.from("carriers").insert(value).select("id").single();if(result.error)return fail(safe(result.error,"No fue posible guardar el transportista."));refresh();return{ok:true,message:pid?"Transportista actualizado.":"Transportista creado.",redirectTo:`/app/transportistas/${result.data.id}`};}
export async function setCarrierStatusAction(id:unknown,active:unknown):Promise<ActionResult>{const parsed=shippingIdSchema.safeParse(id);if(!parsed.success||typeof active!=="boolean")return fail();const c=await context(true);if(!c)return fail("Acción reservada para administradores activos.");const result=await c.supabase.from("carriers").update({is_active:active}).eq("id",parsed.data).select("id").single();if(result.error)return fail(safe(result.error,"No fue posible cambiar el estado."));refresh();return{ok:true,message:active?"Transportista activado.":"Transportista desactivado."};}
export async function createShipmentAction(input:unknown):Promise<ActionResult>{const parsed=shipmentSchema.safeParse(input);if(!parsed.success)return fail(parsed.error.issues[0]?.message);const c=await context();if(!c)return fail("Acción no autorizada.");const v=parsed.data;const {data,error}=await c.supabase.rpc("create_shipment",{p_order_id:v.orderId,p_carrier_id:v.carrierId,p_recipient_name:v.recipientName,p_recipient_phone:v.recipientPhone,p_address_line:v.addressLine,p_district:v.district,p_province:v.province,p_department:v.department,p_address_reference:v.addressReference,p_shipping_cost:v.shippingCost,p_tracking_number:v.trackingNumber,p_notes:v.notes});if(error||!data)return fail(safe(error??{message:"no rows"},"No fue posible crear el envío."));refresh(data);return{ok:true,message:"Envío creado.",redirectTo:`/app/envios/${data}`};}
export async function addShipmentItemAction(input:unknown):Promise<ActionResult>{const parsed=shipmentItemSchema.safeParse(input);if(!parsed.success)return fail(parsed.error.issues[0]?.message);const c=await context();if(!c)return fail("Acción no autorizada.");const {data,error}=await c.supabase.rpc("add_shipment_item",{p_shipment_id:parsed.data.shipmentId,p_order_item_id:parsed.data.orderItemId,p_quantity:parsed.data.quantity});if(error||!data)return fail(safe(error??{message:"no rows"},"No fue posible añadir la línea."));refresh(parsed.data.shipmentId);return{ok:true,message:"Línea añadida."};}
export async function removeShipmentItemAction(id:unknown):Promise<ActionResult>{const parsed=shippingIdSchema.safeParse(id),c=await context();if(!parsed.success||!c)return fail("Acción no autorizada.");const {data,error}=await c.supabase.rpc("remove_shipment_item",{p_shipment_item_id:parsed.data});if(error||!data)return fail(safe(error??{message:"no rows"},"No fue posible retirar la línea."));refresh(data);return{ok:true,message:"Línea retirada."};}
type RpcName="mark_shipment_ready"|"hand_shipment_to_carrier"|"add_shipment_transit_event"|"deliver_shipment"|"start_shipment_return"|"complete_shipment_return";
async function transition(name:RpcName,input:unknown,message:string){const parsed=shipmentTransitionSchema.safeParse(input);if(!parsed.success)return fail(parsed.error.issues[0]?.message);const c=await context();if(!c)return fail("Acción no autorizada.");const args=name==="mark_shipment_ready"?{p_shipment_id:parsed.data.shipmentId,p_idempotency_key:parsed.data.idempotencyKey}:{p_shipment_id:parsed.data.shipmentId,p_location:parsed.data.location,p_description:parsed.data.description,p_idempotency_key:parsed.data.idempotencyKey};const {data,error}=await c.supabase.rpc(name,args as never);if(error||!data)return fail(safe(error??{message:"no rows"},"No fue posible actualizar el envío."));refresh(parsed.data.shipmentId);return{ok:true,message} satisfies ActionResult;}
export async function markShipmentReadyAction(input:unknown){return transition("mark_shipment_ready",input,"Envío preparado.");}
export async function handShipmentToCarrierAction(input:unknown){return transition("hand_shipment_to_carrier",input,"Entrega al transportista registrada.");}
export async function addShipmentTransitEventAction(input:unknown){return transition("add_shipment_transit_event",input,"Actualización de tránsito registrada.");}
export async function deliverShipmentAction(input:unknown){return transition("deliver_shipment",input,"Entrega registrada.");}
export async function startShipmentReturnAction(input:unknown){return transition("start_shipment_return",input,"Retorno iniciado.");}
export async function completeShipmentReturnAction(input:unknown){return transition("complete_shipment_return",input,"Retorno completado.");}
export async function registerDeliveryAttemptAction(input:unknown):Promise<ActionResult>{const parsed=deliveryAttemptSchema.safeParse(input);if(!parsed.success)return fail(parsed.error.issues[0]?.message);const c=await context();if(!c)return fail("Acción no autorizada.");const {data,error}=await c.supabase.rpc("register_delivery_attempt",{p_shipment_id:parsed.data.shipmentId,p_delivered:parsed.data.delivered,p_location:parsed.data.location,p_description:parsed.data.description,p_idempotency_key:parsed.data.idempotencyKey});if(error||!data)return fail(safe(error??{message:"no rows"},"No fue posible registrar el intento."));refresh(parsed.data.shipmentId);return{ok:true,message:parsed.data.delivered?"Entrega registrada.":"Intento fallido registrado."};}
export async function cancelShipmentAction(input:unknown):Promise<ActionResult>{const parsed=shipmentTransitionSchema.safeParse(input);if(!parsed.success)return fail(parsed.error.issues[0]?.message);const c=await context(true);if(!c)return fail("Acción reservada para administradores activos.");const {data,error}=await c.supabase.rpc("cancel_shipment",{p_shipment_id:parsed.data.shipmentId,p_description:parsed.data.description,p_idempotency_key:parsed.data.idempotencyKey});if(error||!data)return fail(safe(error??{message:"no rows"},"No fue posible cancelar el envío."));refresh(parsed.data.shipmentId);return{ok:true,message:"Envío cancelado."};}
export async function runShippingReconciliationAction():Promise<ActionResult>{const c=await context(true);if(!c)return fail("Acción reservada para administradores activos.");const {data,error}=await c.supabase.rpc("admin_shipping_reconciliation");if(error)return fail(safe(error,"No fue posible ejecutar la conciliación."));return{ok:true,message:data.length?`Se detectaron ${data.length} observaciones logísticas.`:"No se detectaron observaciones logísticas."};}
