import Link from "next/link";
import { requireActiveUser } from "@/lib/auth/session";
import { parseSalesFilters } from "@/features/sales/filters";
import { listCustomers } from "@/services/sales";
import { OperationalPagination } from "@/components/inventory/inventory-ui";
import { EmptyState, FilterBar, PageHeader, ResponsiveList, StatusBadge, buttonStyles, fieldClass, tableCellClass, tableClass, tableHeadClass, tableRowClass } from "@/components/ui/operational-ui";
import { Icon } from "@/components/ui/icons";

export default async function Page({ searchParams }: { searchParams: Promise<Record<string,string|string[]|undefined>> }) {
  await requireActiveUser(); const filters=parseSalesFilters(await searchParams); const result=await listCustomers(filters);
  const createAction=<Link href="/app/clientes/nuevo" className={buttonStyles.primary}><Icon name="plus" className="size-4"/>Nuevo cliente</Link>;
  const firstClientAction=<Link href="/app/clientes/nuevo" className={buttonStyles.primary}><Icon name="plus" className="size-4"/>Registrar primer cliente</Link>;
  return <section><PageHeader title="Clientes" description="Directorio privado para pedidos, pagos y seguimiento comercial." action={createAction}/><form><FilterBar className="grid gap-3 sm:grid-cols-[minmax(16rem,1fr)_12rem_auto] sm:items-end"><label className="text-sm font-medium text-slate-700">Buscar<input name="query" defaultValue={filters.query} placeholder="Código, nombre o documento" className={fieldClass}/></label><label className="text-sm font-medium text-slate-700">Estado<select name="status" defaultValue={filters.status} className={fieldClass}><option value="all">Todos</option><option value="active">Activos</option><option value="inactive">Inactivos</option></select></label><button className={buttonStyles.primary}>Aplicar filtros</button></FilterBar></form>
    {result.items.length?<ResponsiveList table={<table className={tableClass}><thead className={tableHeadClass}><tr><th className={tableCellClass}>Cliente</th><th className={tableCellClass}>Código</th><th className={tableCellClass}>Estado</th><th className={`${tableCellClass} text-right`}>Acción</th></tr></thead><tbody>{result.items.map((item)=><tr key={item.id} className={tableRowClass}><td className={`${tableCellClass} font-semibold text-slate-900`}>{item.fullName}</td><td className={`${tableCellClass} font-mono text-xs text-slate-600`}>{item.code}</td><td className={tableCellClass}><StatusBadge label={item.isActive?"Activo":"Inactivo"} tone={item.isActive?"success":"neutral"}/></td><td className={`${tableCellClass} text-right`}><Link href={`/app/clientes/${item.id}`} className="font-semibold text-emerald-700 hover:text-emerald-900">Ver detalle</Link></td></tr>)}</tbody></table>} cards={result.items.map((item)=><Link href={`/app/clientes/${item.id}`} key={item.id} className="rounded-xl border border-slate-200 bg-white p-4 shadow-sm"><div className="flex items-start justify-between gap-3"><div><h2 className="font-semibold text-slate-950">{item.fullName}</h2><p className="mt-1 font-mono text-xs text-slate-500">{item.code}</p></div><StatusBadge label={item.isActive?"Activo":"Inactivo"} tone={item.isActive?"success":"neutral"}/></div></Link>)}/>:<EmptyState title="Todavía no hay clientes" description="Registra el primer cliente para empezar a crear pedidos y pagos." action={firstClientAction} icon="customers"/>}
    <OperationalPagination basePath="/app/clientes" page={result.page} pageCount={result.pageCount} params={{query:filters.query,status:filters.status}}/></section>;
}
