import "server-only";
import { createClient } from "@/lib/supabase/server";
import type { CustomerListItem,Option,OrderDetail,OrderItem,OrderListItem,PageResult,PaymentListItem,SalesFilters } from "@/types/sales";
import { SALES_PAGE_SIZE } from "@/types/sales";

const clean=(value:string)=>value.replace(/[^\p{L}\p{N}\s._-]/gu," ").trim();
const page=<T>(items:T[],total:number,current:number):PageResult<T>=>({items,total,page:current,pageSize:SALES_PAGE_SIZE,pageCount:Math.max(1,Math.ceil(total/SALES_PAGE_SIZE))});
const bounds=(current:number)=>({from:(current-1)*SALES_PAGE_SIZE,to:current*SALES_PAGE_SIZE-1});
const unique=(values:string[])=>[...new Set(values)];

export async function listCustomers(filters:SalesFilters){const supabase=await createClient();const b=bounds(filters.page);let q=supabase.from("customers").select("id,code,full_name,document_type,document_number,email,phone,address,notes,is_active",{count:"exact"});if(filters.query)q=q.or(`code.ilike.%${clean(filters.query)}%,full_name.ilike.%${clean(filters.query)}%,document_number.ilike.%${clean(filters.query)}%`);if(filters.status==="active")q=q.eq("is_active",true);if(filters.status==="inactive")q=q.eq("is_active",false);const {data,error,count}=await q.order("full_name").range(b.from,b.to);if(error)throw new Error("No fue posible cargar los clientes.");return page<CustomerListItem>(data.map(v=>({id:v.id,code:v.code,fullName:v.full_name,documentType:v.document_type,documentNumber:v.document_number,email:v.email,phone:v.phone,address:v.address,notes:v.notes,isActive:v.is_active})),count??0,filters.page);}
export async function getCustomer(id:string){const supabase=await createClient();const {data,error}=await supabase.from("customers").select("id,code,full_name,document_type,document_number,email,phone,address,notes,is_active").eq("id",id).maybeSingle();if(error)throw new Error("No fue posible cargar el cliente.");return data?{id:data.id,code:data.code,fullName:data.full_name,documentType:data.document_type,documentNumber:data.document_number,email:data.email,phone:data.phone,address:data.address,notes:data.notes,isActive:data.is_active}:null;}
export async function listCustomerOptions():Promise<Option[]>{const supabase=await createClient();const {data,error}=await supabase.from("customers").select("id,code,full_name").eq("is_active",true).order("full_name").limit(200);if(error)throw new Error("No fue posible cargar los clientes.");return data.map(v=>({id:v.id,label:`${v.code} · ${v.full_name}`}));}
export async function listBalanceOptions():Promise<Option[]>{const supabase=await createClient();const {data,error}=await supabase.from("inventory_balances").select("id,variant_id,warehouse_id,location_id,available_stock").gt("available_stock",0).limit(300);if(error)throw new Error("No fue posible cargar el inventario.");const variants=await supabase.from("product_variants").select("id,sku,name").in("id",unique(data.map(v=>v.variant_id)));const locations=await supabase.from("warehouse_locations").select("id,code,name").in("id",unique(data.map(v=>v.location_id)));const vm=new Map((variants.data??[]).map(v=>[v.id,`${v.sku} · ${v.name}`]));const lm=new Map((locations.data??[]).map(v=>[v.id,`${v.code} · ${v.name}`]));return data.map(v=>({id:`${v.variant_id}|${v.warehouse_id}|${v.location_id}`,label:`${vm.get(v.variant_id)??"Variante"} · ${lm.get(v.location_id)??"Ubicación"} · disponible ${v.available_stock}`}));}
export async function listReturnLocationOptions():Promise<Option[]>{const supabase=await createClient();const {data,error}=await supabase.from("warehouse_locations").select("id,code,name,warehouse_id").eq("is_active",true).order("code").limit(300);if(error)throw new Error("No fue posible cargar las ubicaciones.");const warehouses=await supabase.from("warehouses").select("id,code,name").eq("is_active",true).in("id",unique(data.map(v=>v.warehouse_id)));const wm=new Map((warehouses.data??[]).map(v=>[v.id,`${v.code} · ${v.name}`]));return data.filter(v=>wm.has(v.warehouse_id)).map(v=>({id:v.id,label:`${wm.get(v.warehouse_id)} · ${v.code} · ${v.name}`}));}
export async function listOrders(filters:SalesFilters){const supabase=await createClient();const b=bounds(filters.page);let q=supabase.from("orders").select("id,order_number,customer_id,status,payment_status,ordered_at,total_amount,paid_amount,balance_due",{count:"exact"});if(filters.status!=="all")q=q.eq("status",filters.status as never);if(filters.query)q=q.ilike("order_number",`%${clean(filters.query)}%`);const {data,error,count}=await q.order("ordered_at",{ascending:false}).range(b.from,b.to);if(error)throw new Error("No fue posible cargar los pedidos.");const customers=await supabase.from("customers").select("id,full_name").in("id",unique(data.map(v=>v.customer_id)));const cm=new Map((customers.data??[]).map(v=>[v.id,v.full_name]));return page<OrderListItem>(data.map(v=>({id:v.id,orderNumber:v.order_number,customerId:v.customer_id,customerName:cm.get(v.customer_id)??"Cliente no disponible",status:v.status,paymentStatus:v.payment_status,orderedAt:v.ordered_at,totalAmount:v.total_amount,paidAmount:v.paid_amount,balanceDue:v.balance_due})),count??0,filters.page);}
export async function getOrder(id:string):Promise<OrderDetail|null>{const supabase=await createClient();const {data:o,error}=await supabase.from("orders").select("id,order_number,customer_id,status,payment_status,ordered_at,total_amount,paid_amount,balance_due,notes").eq("id",id).maybeSingle();if(error)throw new Error("No fue posible cargar el pedido.");if(!o)return null;const [{data:c},{data:rows,error:re}]=await Promise.all([supabase.from("customers").select("full_name").eq("id",o.customer_id).maybeSingle(),supabase.from("order_items").select("id,order_id,line_number,variant_id,warehouse_id,location_id,quantity,reserved_quantity,dispatched_quantity,returned_quantity,unit_cost_snapshot,unit_price,discount_amount,tax_amount,line_total").eq("order_id",id).order("line_number")]);if(re)throw new Error("No fue posible cargar las líneas.");const variants=await supabase.from("product_variants").select("id,sku,name").in("id",unique(rows.map(v=>v.variant_id)));const locations=await supabase.from("warehouse_locations").select("id,code,name").in("id",unique(rows.map(v=>v.location_id)));const vm=new Map((variants.data??[]).map(v=>[v.id,`${v.sku} · ${v.name}`]));const lm=new Map((locations.data??[]).map(v=>[v.id,`${v.code} · ${v.name}`]));const items:OrderItem[]=rows.map(v=>({id:v.id,orderId:v.order_id,lineNumber:v.line_number,variantId:v.variant_id,variantLabel:vm.get(v.variant_id)??"Variante",warehouseId:v.warehouse_id,locationId:v.location_id,locationLabel:lm.get(v.location_id)??"Ubicación",quantity:v.quantity,reservedQuantity:v.reserved_quantity,dispatchedQuantity:v.dispatched_quantity,returnedQuantity:v.returned_quantity,unitCostSnapshot:v.unit_cost_snapshot,unitPrice:v.unit_price,discountAmount:v.discount_amount,taxAmount:v.tax_amount,lineTotal:v.line_total}));return{id:o.id,orderNumber:o.order_number,customerId:o.customer_id,customerName:c?.full_name??"Cliente",status:o.status,paymentStatus:o.payment_status,orderedAt:o.ordered_at,totalAmount:o.total_amount,paidAmount:o.paid_amount,balanceDue:o.balance_due,notes:o.notes,items};}
export async function listPayments(filters:SalesFilters){const supabase=await createClient();const b=bounds(filters.page);let q=supabase.from("payments").select("id,payment_number,order_id,amount,method,status,refunded_payment_id,paid_at,reference,notes",{count:"exact"});if(filters.status!=="all")q=q.eq("status",filters.status as never);if(filters.query)q=q.or(`payment_number.ilike.%${clean(filters.query)}%,reference.ilike.%${clean(filters.query)}%`);const {data,error,count}=await q.order("created_at",{ascending:false}).range(b.from,b.to);if(error)throw new Error("No fue posible cargar los pagos.");const orders=await supabase.from("orders").select("id,order_number").in("id",unique(data.map(v=>v.order_id)));const om=new Map((orders.data??[]).map(v=>[v.id,v.order_number]));return page<PaymentListItem>(data.map(v=>({id:v.id,paymentNumber:v.payment_number,orderId:v.order_id,orderNumber:om.get(v.order_id)??"Pedido",amount:v.amount,method:v.method,status:v.status,refundedPaymentId:v.refunded_payment_id,paidAt:v.paid_at,reference:v.reference,notes:v.notes})),count??0,filters.page);}
export async function getPayment(id:string):Promise<PaymentListItem|null>{const supabase=await createClient();const {data:v,error}=await supabase.from("payments").select("id,payment_number,order_id,amount,method,status,refunded_payment_id,paid_at,reference,notes").eq("id",id).maybeSingle();if(error)throw new Error("No fue posible cargar el pago.");if(!v)return null;const {data:o}=await supabase.from("orders").select("order_number").eq("id",v.order_id).maybeSingle();return{id:v.id,paymentNumber:v.payment_number,orderId:v.order_id,orderNumber:o?.order_number??"Pedido",amount:v.amount,method:v.method,status:v.status,refundedPaymentId:v.refunded_payment_id,paidAt:v.paid_at,reference:v.reference,notes:v.notes};}
export async function listOrderOptions():Promise<Option[]>{const supabase=await createClient();const {data,error}=await supabase.from("orders").select("id,order_number,total_amount,paid_amount").not("status","in","(cancelled,returned)").order("created_at",{ascending:false}).limit(200);if(error)throw new Error("No fue posible cargar los pedidos.");return data.map(v=>({id:v.id,label:`${v.order_number} · saldo ${v.total_amount-v.paid_amount}`}));}
