"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import type { ActionResult } from "@/app/actions/auth";
import {
  cancelOrderAction, cancelPaymentAction, checkCustomerDuplicatesAction, confirmOrderAction,
  confirmPaymentAction, deliverOrderAction, dispatchOrderAction, dispatchOrderItemAction,
  refundPaymentAction, removeOrderItemAction, returnOrderItemAction, returnOrderToDraftAction,
  runFinancialReconciliationAction, saveCustomerAction, saveOrderAction, saveOrderItemAction,
  savePaymentAction, setCustomerStatusAction, submitOrderAction,
} from "@/app/actions/sales";
import { ConfirmDialog, Modal } from "@/components/ui/dialog";
import { Feedback, FormField, buttonStyles, fieldClass } from "@/components/ui/operational-ui";
import { formatDateTimeLocalInLima } from "@/features/inventory/lima-time";
import { paymentMethodLabels } from "@/features/sales/domain";
import type { CustomerListItem, Option, OrderDetail, OrderItem, PaymentListItem } from "@/types/sales";

function useMutation() {
  const router = useRouter(); const [pending, start] = useTransition(); const [result, setResult] = useState<ActionResult>({ ok: false, message: "" });
  const run = (work: () => Promise<ActionResult>) => { if (pending) return; start(async () => { const next = await work(); setResult(next); if (next.ok) { if (next.redirectTo) router.push(next.redirectTo); router.refresh(); } }); };
  return { pending, result, run, setResult };
}

function Message({ result }: { result: ActionResult }) { return result.message ? <Feedback tone={result.ok ? "success" : "error"}>{result.message}</Feedback> : null; }
function Submit({ pending, label = "Guardar" }: { pending: boolean; label?: string }) { return <button disabled={pending} className={buttonStyles.primary}>{pending ? "Procesando…" : label}</button>; }

export function CustomerForm({ customer }: { customer?: CustomerListItem }) {
  const mutation = useMutation();
  const values = (form: FormData) => ({ fullName: form.get("fullName"), documentType: form.get("documentType"), documentNumber: form.get("documentNumber"), email: form.get("email"), phone: form.get("phone"), address: form.get("address"), notes: form.get("notes") });
  return <form onSubmit={(event) => { event.preventDefault(); mutation.run(() => saveCustomerAction(customer?.id ?? null, values(new FormData(event.currentTarget)))); }} className="grid gap-4 sm:grid-cols-2">
    <FormField label="Nombre completo" required><input name="fullName" required defaultValue={customer?.fullName} className={fieldClass}/></FormField>
    <FormField label="Correo"><input name="email" type="email" defaultValue={customer?.email ?? ""} className={fieldClass}/></FormField>
    <FormField label="Tipo de documento"><input name="documentType" defaultValue={customer?.documentType ?? ""} className={fieldClass}/></FormField>
    <FormField label="Número de documento"><input name="documentNumber" defaultValue={customer?.documentNumber ?? ""} className={fieldClass}/></FormField>
    <FormField label="Teléfono"><input name="phone" defaultValue={customer?.phone ?? ""} className={fieldClass}/></FormField>
    <FormField label="Dirección"><input name="address" defaultValue={customer?.address ?? ""} className={fieldClass}/></FormField>
    <FormField label="Notas" className="sm:col-span-2"><textarea name="notes" rows={3} defaultValue={customer?.notes ?? ""} className={fieldClass}/></FormField>
    <div className="sm:col-span-2"><Message result={mutation.result}/></div>
    <div className="flex flex-wrap justify-end gap-2 sm:col-span-2">{!customer ? <button type="button" disabled={mutation.pending} onClick={(event) => { const form = event.currentTarget.form; if (form) mutation.run(() => checkCustomerDuplicatesAction(values(new FormData(form)))); }} className={buttonStyles.secondary}>Revisar duplicados</button> : null}<Submit pending={mutation.pending}/></div>
  </form>;
}

export function CustomerStatusButton({ customer }: { customer: CustomerListItem }) {
  const mutation = useMutation(); const [open, setOpen] = useState(false);
  return <div className="space-y-2"><button type="button" disabled={mutation.pending} onClick={()=>setOpen(true)} className={customer.isActive ? buttonStyles.danger : buttonStyles.secondary}>{customer.isActive ? "Desactivar" : "Activar"}</button><ConfirmDialog open={open} onOpenChange={setOpen} title={customer.isActive ? "Desactivar cliente" : "Activar cliente"} description={customer.isActive ? "El cliente dejará de estar disponible para nuevos pedidos. Los registros históricos se conservarán." : "El cliente volverá a estar disponible para la operación."} confirmLabel={customer.isActive ? "Desactivar cliente" : "Activar cliente"} danger={customer.isActive} pending={mutation.pending} onConfirm={()=>{setOpen(false);mutation.run(()=>setCustomerStatusAction(customer.id,!customer.isActive));}}/><Message result={mutation.result}/></div>;
}

export function OrderForm({ order, customers }: { order?: OrderDetail; customers: Option[] }) {
  const mutation=useMutation();
  return <form onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);mutation.run(()=>saveOrderAction(order?.id??null,{customerId:form.get("customerId"),orderedAt:form.get("orderedAt"),notes:form.get("notes")}));}} className="grid gap-4 sm:grid-cols-2"><FormField label="Cliente" required><select name="customerId" defaultValue={order?.customerId} required className={fieldClass}><option value="">Selecciona un cliente</option>{customers.map((value)=><option key={value.id} value={value.id}>{value.label}</option>)}</select></FormField><FormField label="Fecha y hora de Lima" required><input name="orderedAt" type="datetime-local" required defaultValue={order ? formatDateTimeLocalInLima(order.orderedAt) ?? "" : formatDateTimeLocalInLima() ?? ""} className={fieldClass}/></FormField><FormField label="Notas" className="sm:col-span-2"><textarea name="notes" rows={3} defaultValue={order?.notes??""} className={fieldClass}/></FormField><div className="sm:col-span-2"><Message result={mutation.result}/></div><div className="flex justify-end sm:col-span-2"><Submit pending={mutation.pending}/></div></form>;
}

export function OrderItemForm({ orderId, item, balances }: { orderId: string; item?: OrderItem; balances: Option[] }) {
  const mutation=useMutation(); const existing=item?`${item.variantId}|${item.warehouseId}|${item.locationId}`:"";
  return <form onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);const [variantId,warehouseId,locationId]=String(form.get("balance")).split("|");mutation.run(()=>saveOrderItemAction(item?.id??null,{orderId,lineNumber:form.get("lineNumber"),variantId,warehouseId,locationId,quantity:form.get("quantity"),unitPrice:form.get("unitPrice"),discountAmount:form.get("discountAmount"),taxAmount:form.get("taxAmount")}));}} className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3"><FormField label="Línea" required><input name="lineNumber" type="number" min="1" required defaultValue={item?.lineNumber??1} className={fieldClass}/></FormField><FormField label="Balance exacto" required><select name="balance" required defaultValue={existing} className={fieldClass}><option value="">Selecciona producto y ubicación</option>{balances.map((value)=><option key={value.id} value={value.id}>{value.label}</option>)}</select></FormField><FormField label="Cantidad" required><input name="quantity" type="number" step="0.001" min="0.001" required defaultValue={item?.quantity??1} className={fieldClass}/></FormField><FormField label="Precio unitario" required><input name="unitPrice" type="number" step="0.01" min="0" required defaultValue={item?.unitPrice??0} className={fieldClass}/></FormField><FormField label="Descuento" help="No puede superar el subtotal."><input name="discountAmount" type="number" step="0.01" min="0" defaultValue={item?.discountAmount??0} className={fieldClass}/></FormField><FormField label="Impuesto"><input name="taxAmount" type="number" step="0.01" min="0" defaultValue={item?.taxAmount??0} className={fieldClass}/></FormField><div className="sm:col-span-2 xl:col-span-3"><Message result={mutation.result}/></div><div className="flex justify-end sm:col-span-2 xl:col-span-3"><Submit pending={mutation.pending} label="Guardar línea"/></div></form>;
}

export function OrderActions({ order }: { order: OrderDetail }) {
  const mutation=useMutation(); const [dialog,setDialog]=useState<"confirm"|"dispatch"|"deliver"|"cancel"|null>(null); const key=()=>crypto.randomUUID(); const canCancel=["draft","new","confirmed"].includes(order.status)||(order.status==="preparing"&&order.items.every((value)=>value.dispatchedQuantity===0));
  return <div className="flex flex-wrap gap-2">
    {order.status==="draft"?<button type="button" disabled={mutation.pending} onClick={()=>mutation.run(()=>submitOrderAction(order.id))} className={buttonStyles.primary}>Enviar pedido</button>:null}
    {order.status==="new"?<><button type="button" disabled={mutation.pending} onClick={()=>setDialog("confirm")} className={buttonStyles.primary}>Confirmar pedido</button><button type="button" disabled={mutation.pending} onClick={()=>mutation.run(()=>returnOrderToDraftAction(order.id))} className={buttonStyles.secondary}>Volver a borrador</button></>:null}
    {order.status==="confirmed"||order.status==="preparing"?<button type="button" disabled={mutation.pending} onClick={()=>setDialog("dispatch")} className={buttonStyles.primary}>Despachar pedido</button>:null}
    {order.status==="shipped"?<button type="button" disabled={mutation.pending} onClick={()=>setDialog("deliver")} className={buttonStyles.primary}>Marcar entregado</button>:null}
    {canCancel?<button type="button" disabled={mutation.pending} onClick={()=>setDialog("cancel")} className={buttonStyles.danger}>Cancelar</button>:null}
    <ConfirmDialog open={dialog==="confirm"} onOpenChange={(open)=>setDialog(open?"confirm":null)} title="Confirmar pedido" description="Se reservará el stock de todas las líneas con disponibilidad suficiente." confirmLabel="Confirmar pedido" pending={mutation.pending} onConfirm={()=>{setDialog(null);mutation.run(()=>confirmOrderAction(order.id,key()));}}/>
    <ConfirmDialog open={dialog==="dispatch"} onOpenChange={(open)=>setDialog(open?"dispatch":null)} title="Despachar pedido" description="Se descontará el stock físico reservado y el pedido avanzará según las cantidades despachadas." confirmLabel="Despachar" pending={mutation.pending} onConfirm={()=>{setDialog(null);mutation.run(()=>dispatchOrderAction(order.id,key()));}}/>
    <ConfirmDialog open={dialog==="deliver"} onOpenChange={(open)=>setDialog(open?"deliver":null)} title="Confirmar entrega" description="El pedido quedará marcado como entregado." confirmLabel="Marcar entregado" pending={mutation.pending} onConfirm={()=>{setDialog(null);mutation.run(()=>deliverOrderAction(order.id));}}/>
    <ConfirmDialog open={dialog==="cancel"} onOpenChange={(open)=>setDialog(open?"cancel":null)} title="Cancelar pedido" description="Las reservas existentes se liberarán. El pedido conservará su historial." confirmLabel="Cancelar pedido" danger pending={mutation.pending} onConfirm={()=>{setDialog(null);mutation.run(()=>cancelOrderAction(order.id,key()));}}/>
    <div className="basis-full"><Message result={mutation.result}/></div>
  </div>;
}

export function OrderItemActions({ item, returnLocations }: { item: OrderItem; returnLocations: Option[] }) {
  const mutation=useMutation(); const [dialog,setDialog]=useState<"remove"|"dispatch"|null>(null); const [returnOpen,setReturnOpen]=useState(false); const [locationId,setLocationId]=useState(returnLocations[0]?.id??""); const remaining=item.dispatchedQuantity-item.returnedQuantity; const [quantity,setQuantity]=useState(remaining); const [reason,setReason]=useState(""); const [localError,setLocalError]=useState("");
  const submitReturn=()=>{if(!locationId||!Number.isFinite(quantity)||quantity<=0||quantity>remaining||!reason.trim()){setLocalError("Completa una ubicación, una cantidad válida y la razón de devolución.");return;}setReturnOpen(false);setLocalError("");mutation.run(()=>returnOrderItemAction({itemId:item.id,locationId,quantity,reason,idempotencyKey:crypto.randomUUID()}));};
  return <div className="flex flex-wrap items-center gap-2"><button type="button" disabled={mutation.pending} onClick={()=>setDialog("remove")} className={buttonStyles.ghost}>Retirar</button>{item.reservedQuantity>0?<button type="button" disabled={mutation.pending} onClick={()=>setDialog("dispatch")} className={buttonStyles.secondary}>Despachar reserva</button>:null}{remaining>0&&returnLocations.length>0?<button type="button" disabled={mutation.pending} onClick={()=>{setQuantity(remaining);setReturnOpen(true);}} className={buttonStyles.secondary}>Registrar devolución</button>:null}
    <ConfirmDialog open={dialog==="remove"} onOpenChange={(open)=>setDialog(open?"remove":null)} title="Retirar línea" description="La línea será retirada del pedido en borrador." confirmLabel="Retirar" danger pending={mutation.pending} onConfirm={()=>{setDialog(null);mutation.run(()=>removeOrderItemAction(item.id));}}/>
    <ConfirmDialog open={dialog==="dispatch"} onOpenChange={(open)=>setDialog(open?"dispatch":null)} title="Despachar línea" description={`Se despacharán ${item.reservedQuantity} unidades reservadas.`} confirmLabel="Despachar" pending={mutation.pending} onConfirm={()=>{setDialog(null);mutation.run(()=>dispatchOrderItemAction({itemId:item.id,quantity:item.reservedQuantity,idempotencyKey:crypto.randomUUID()}));}}/>
    <Modal open={returnOpen} onClose={()=>setReturnOpen(false)} title="Registrar devolución" description="El movimiento ingresará a la ubicación seleccionada con el costo histórico de la venta." footer={<><button type="button" className={buttonStyles.secondary} onClick={()=>setReturnOpen(false)}>Cancelar</button><button type="button" className={buttonStyles.primary} onClick={submitReturn} disabled={mutation.pending}>Registrar devolución</button></>}><div className="space-y-4"><FormField label="Ubicación de devolución" required><select value={locationId} onChange={(event)=>setLocationId(event.target.value)} className={fieldClass}>{returnLocations.map((value)=><option key={value.id} value={value.id}>{value.label}</option>)}</select></FormField><FormField label="Cantidad" required help={`Máximo disponible para devolver: ${remaining}.`}><input type="number" min="0.001" max={remaining} step="0.001" value={quantity} onChange={(event)=>setQuantity(Number(event.target.value))} className={fieldClass}/></FormField><FormField label="Razón" required><textarea rows={3} value={reason} onChange={(event)=>setReason(event.target.value)} className={fieldClass}/></FormField>{localError?<Feedback tone="error">{localError}</Feedback>:null}</div></Modal>
    <div className="basis-full"><Message result={mutation.result}/></div>
  </div>;
}

export function PaymentForm({ payment, orders }: { payment?: PaymentListItem; orders: Option[] }) {
  const mutation=useMutation(); return <form onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);mutation.run(()=>savePaymentAction(payment?.id??null,{orderId:form.get("orderId"),amount:form.get("amount"),method:form.get("method"),reference:form.get("reference"),notes:form.get("notes")}));}} className="grid gap-4 sm:grid-cols-2"><FormField label="Pedido" required><select name="orderId" required defaultValue={payment?.orderId} className={fieldClass}><option value="">Selecciona un pedido</option>{orders.map((value)=><option key={value.id} value={value.id}>{value.label}</option>)}</select></FormField><FormField label="Importe PEN" required><input name="amount" type="number" min="0.01" step="0.01" required defaultValue={payment?.amount} className={fieldClass}/></FormField><FormField label="Método" required><select name="method" defaultValue={payment?.method} className={fieldClass}>{Object.entries(paymentMethodLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></FormField><FormField label="Referencia"><input name="reference" defaultValue={payment?.reference??""} className={fieldClass}/></FormField><FormField label="Notas" className="sm:col-span-2"><textarea name="notes" rows={3} defaultValue={payment?.notes??""} className={fieldClass}/></FormField><div className="sm:col-span-2"><Message result={mutation.result}/></div><div className="flex justify-end sm:col-span-2"><Submit pending={mutation.pending}/></div></form>;
}

export function PaymentActions({ payment, isAdmin }: { payment: PaymentListItem; isAdmin: boolean }) {
  const mutation=useMutation(); const [dialog,setDialog]=useState<"confirm"|"cancel"|null>(null); const [refundOpen,setRefundOpen]=useState(false); const [amount,setAmount]=useState(payment.amount); const [reason,setReason]=useState(""); const [localError,setLocalError]=useState("");
  const submitRefund=()=>{if(!Number.isFinite(amount)||amount<=0||!reason.trim()){setLocalError("Ingresa un importe válido y la razón del reembolso.");return;}setRefundOpen(false);setLocalError("");mutation.run(()=>refundPaymentAction({paymentId:payment.id,amount,reason,idempotencyKey:crypto.randomUUID()}));};
  return <div className="flex flex-wrap gap-2">{payment.status==="pending"?<><button type="button" disabled={mutation.pending} onClick={()=>setDialog("confirm")} className={buttonStyles.primary}>Confirmar pago</button><button type="button" disabled={mutation.pending} onClick={()=>setDialog("cancel")} className={buttonStyles.danger}>Cancelar pago</button></>:null}{isAdmin&&payment.status==="paid"?<button type="button" disabled={mutation.pending} onClick={()=>{setAmount(payment.amount);setReason("");setRefundOpen(true);}} className={buttonStyles.danger}>Reembolsar</button>:null}
    <ConfirmDialog open={dialog==="confirm"} onOpenChange={(open)=>setDialog(open?"confirm":null)} title="Confirmar pago" description="El pago quedará confirmado con la fecha y hora actual de Lima." confirmLabel="Confirmar pago" pending={mutation.pending} onConfirm={()=>{setDialog(null);mutation.run(()=>confirmPaymentAction({paymentId:payment.id,paidAt:formatDateTimeLocalInLima()??"",idempotencyKey:crypto.randomUUID()}));}}/>
    <ConfirmDialog open={dialog==="cancel"} onOpenChange={(open)=>setDialog(open?"cancel":null)} title="Cancelar pago" description="El pago pendiente quedará cancelado y no afectará el saldo del pedido." confirmLabel="Cancelar pago" danger pending={mutation.pending} onConfirm={()=>{setDialog(null);mutation.run(()=>cancelPaymentAction(payment.id));}}/>
    <Modal open={refundOpen} onClose={()=>setRefundOpen(false)} title="Registrar reembolso" description="Se creará un registro compensatorio sin modificar el pago original." danger footer={<><button type="button" className={buttonStyles.secondary} onClick={()=>setRefundOpen(false)}>Cancelar</button><button type="button" className={buttonStyles.danger} onClick={submitRefund} disabled={mutation.pending}>Registrar reembolso</button></>}><div className="space-y-4"><FormField label="Importe a reembolsar" required><input type="number" min="0.01" max={payment.amount} step="0.01" value={amount} onChange={(event)=>setAmount(Number(event.target.value))} className={fieldClass}/></FormField><FormField label="Razón" required><textarea rows={3} value={reason} onChange={(event)=>setReason(event.target.value)} className={fieldClass}/></FormField>{localError?<Feedback tone="error">{localError}</Feedback>:null}</div></Modal>
    <div className="basis-full"><Message result={mutation.result}/></div>
  </div>;
}

export function FinancialReconciliationButton() { const mutation=useMutation(); const [open,setOpen]=useState(false); return <div className="space-y-2"><button type="button" disabled={mutation.pending} onClick={()=>setOpen(true)} className={buttonStyles.secondary}>Conciliar pagos</button><ConfirmDialog open={open} onOpenChange={setOpen} title="Ejecutar conciliación" description="Se revisarán saldos y estados derivados. La operación no modifica registros comerciales." confirmLabel="Ejecutar conciliación" pending={mutation.pending} onConfirm={()=>{setOpen(false);mutation.run(runFinancialReconciliationAction);}}/><Message result={mutation.result}/></div>; }
